import Head from "next/head";
import Image from "next/image";

export default function Home() {
  let btnClass =
    "bg-red-500 btn-signup pt-3 pb-3 pl-5 pr-5 rounded-full text-white";
  return (
    <>
      <Head>
        <title>Mindful Athlete</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="/dist/output.css" />
      </Head>
      <div className="body ">
        <div className="header flex justify-between items-center pt-5">
          <h1 className="text-5xl mx-auto text-white">mindful athlete</h1>
          <div className="navbar space-x-4 mr-4 text-white">
            <a href="#">Home</a>
            <a href="#">About</a>
            <a href="#" className="">
              Sign in
            </a>
            <a href="#" className={btnClass}>
              GET STARTED
            </a>
          </div>
        </div>
        <main>
          <div className="content text-center mt-96">
            <h1 className="text-8xl text-center mb-5 text-white">
              BREAK YOUR LIMITS WITH <br /> MINDFUL ATHLETE
            </h1>
            <a href="#" className={btnClass}>
              GET STARTED
            </a>
          </div>
        </main>
      </div>
    </>
  );
}
